[package]
name = "score-tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.relm4]
version = "0.6.2"
features = ["macros", "libadwaita", "gnome_44"]

[dependencies.relm4-icons]
version = "0.6.0"
features = ["table", "hourglass", "plus", "person-add-regular", "person-subtract-regular", "cross-filled"]